networks:
  caddy:
    external: true

services:
  qbittorrent:
    image: ghcr.io/hotio/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
      - WEBUI_PORTS=8080/tcp, 8080/udp
    volumes:
      - ./config/:/config/
      - /mnt/storage/shared/downloads/:/downloads/
    networks:
      - caddy
    restart: unless-stopped
