networks:
  caddy:
    external: true

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./config/:/config/
      - /mnt/storage/shared/downloads/:/downloads/
    ports:
      - 6881:6881
      - 6881:6881/udp
    networks:
      - caddy
    restart: unless-stopped
