networks:
  caddy:
    external: true

services:
  caddy:
    build:
      context: caddy_image/
      dockerfile: ./Dockerfile
    container_name: caddy
    cap_add:
      - NET_ADMIN
    ports:
    - target: 80
      published: 80
      mode: host
    - target: 443
      published: 443
      mode: host
    - target: 443
      published: 443
      protocol: udp
      mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/:/data/
      - ./config/:/config/
    env_file:
      - .env
    restart: always
    networks:
      - caddy
