networks:
  caddy:
    external: true

services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: stirling
    volumes:
      - ./trainingData:/usr/share/tessdata #Required for extra OCR languages
      - ./configs:/configs
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
    networks:
      - caddy
    restart: unless-stopped
