networks:
    caddy:
        external: true

services:
    speedtest-tracker:
        container_name: speedtest-tracker
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Argentina/Buenos_Aires
            - DB_CONNECTION=sqlite
        volumes:
            - ./data/:/config/
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
        networks:
            - caddy
        healthcheck:
            test: curl -fSs https://speedtest.home.fari.ar/api/healthcheck || exit 1
            interval: 10s
            retries: 3
            start_period: 30s
            timeout: 10s
