networks:
  caddy:
    external: true

secrets:
  admin_password:
    file: "./secrets/admin_password"

services:
  dns-server:
    container_name: dns-server
    hostname: dns-server
    image: technitium/dns-server:latest
    ports:
      - "53:53/udp" #DNS service
      - "53:53/tcp" #DNS service
    networks:
      - caddy
    environment:
      - DNS_SERVER_DOMAIN=home.fari.ar #The primary domain name used by this DNS Server to identify itself.
      - DNS_SERVER_ADMIN_PASSWORD_FILE=/run/secrets/admin_password #The path to a file that contains a plain text password for the DNS web console admin user.
      - DNS_SERVER_PREFER_IPV6=false #DNS Server will use IPv6 for querying whenever possible with this option enabled.
      - DNS_SERVER_ALLOW_TXT_BLOCKING_REPORT=false #Specifies if the DNS Server should respond with TXT records containing a blocked domain report for TXT type requests.
      - DNS_SERVER_OPTIONAL_PROTOCOL_DNS_OVER_HTTP=false #Enables DNS server optional protocol DNS-over-HTTP on TCP port 8053 to be used with a TLS terminating reverse proxy like nginx.
      # ----------
      # Web service
      - DNS_SERVER_WEB_SERVICE_LOCAL_ADDRESSES-127.0.0.1, 192.168.100.0/24, 192.168.195.0/24
      - DNS_SERVER_WEB_SERVICE_HTTP_PORT=5380 #The TCP port number for the DNS web console over HTTP protocol.
      - DNS_SERVER_WEB_SERVICE_ENABLE_HTTPS=false #Enables HTTPS for the DNS web console.
      # ----------
      # Recursion
      - DNS_SERVER_RECURSION=UseSpecifiedNetworks #Recursion options: Allow, Deny, AllowOnlyForPrivateNetworks, UseSpecifiedNetworks.
      - DNS_SERVER_RECURSION_ALLOWED_NETWORKS=127.0.0.1, 192.168.100.0/24, 192.168.195.0/24 #Comma separated list of IP addresses or network addresses to allow recursion. Valid only for `UseSpecifiedNetworks` recursion option.
      # ----------
      # Forward
      - DNS_SERVER_FORWARDERS=1.1.1.1, 1.1.0.1 #Comma separated list of forwarder addresses.
      - DNS_SERVER_FORWARDER_PROTOCOL=Tcp #Forwarder protocol options: Udp, Tcp, Tls, Https, HttpsJson.
      - DNS_SERVER_LOG_USING_LOCAL_TIME=true #Enable this option to use local time instead of UTC for logging.
    volumes:
      - config:/etc/dns
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
    secrets:
      - admin_password
 
volumes:
    config:
      driver: local
