networks:
  caddy:
    external: true

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    environment:
      - DOCKER_MODS=linuxserver/mods:jellyfin-amd
    ports:
      - 8096:8096
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    networks:
      - caddy
    volumes:
      - ./config/:/config/
      - ./cache/:/cache/
      - type: bind
        source: /mnt/storage/shared/downloads/multimedia/
        target: /media
        read_only: true
    devices:
      - /dev/dri:/dev/dri
    restart: 'unless-stopped'
