networks:
  caddy:
    external: true

services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
      - ENV=/data
    volumes:
      - ./config/:/config/
      - /mnt/storage/syncthing/data/:/data/
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    networks:
      - caddy
    restart: unless-stopped
