---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services
#

- Multimedia:
    - Jellyfin:
        icon: jellyfin.png
        description: Media Server
        href: https://jellyfin.home.fari.ar
        container: jellyfin
        server: docker-proxy-local
        widget:
            type: jellyfin
            url: http://jellyfin:8096
            key: {{HOMEPAGE_VAR_JELLYFIN_API_KEY}}
            enableBlocks: true # optional, defaults to false
            enableNowPlaying: true # optional, defaults to true
            enableUser: true # optional, defaults to false
            showEpisodeNumber: true # optional, defaults to false
            expandOneStreamToTwoRows: false # optional, defaults to true

- File sharing:
    - Filebrowser:
        icon: filebrowser.png
        description: Web based file browser
        href: https://filebrowser.home.fari.ar
        container: filebrowser
        server: docker-proxy-local
    - Syncthing:
        icon: syncthing.png
        description: Peer-to-peer file synchronization
        href: https://sync.home.fari.ar
        container: syncthing
        server: docker-proxy-local
        widget:
            type: customapi
            url: http://syncthing:8384/rest/svc/report
            headers:
                X-API-Key: {{HOMEPAGE_VAR_SYNCTHING_API_KEY}}
            mappings:
                - field: totMiB
                  label: Stored (MB)
                  format: number
                - field: numFolders
                  label: Folders
                  format: number
                - field: totFiles
                  label: Files
                  format: number
                - field: numDevices
                  label: Devices
                  format: number
    - Immich:
        icon: immich.png
        description: Photo and video management
        href: https://photos.home.fari.ar
        container: immich_server
        server: docker-proxy-local
        widget:
            type: immich
            url: http://immich_server:3001
            key: {{HOMEPAGE_VAR_IMMICH_API_KEY}}

- Downloads:
    - qBittorrent:
        icon: qbittorrent.png
        description: Torrent client
        href: https://torrent.home.fari.ar
        container: qbittorrent
        server: docker-proxy-local
        widget:
            type: qbittorrent
            url: http://qbittorrent:8080
            username: admin
            password: {{HOMEPAGE_VAR_QBITTORENT_PASSWORD}}
    - Jdownloader:
        icon: jdownloader.png
        description: Downloads manager
        href: https://jdownloader.home.fari.ar
        container: jdownloader
        server: docker-proxy-local
        widget:
            type: jdownloader
            username: fari@fari.ar
            password: {{HOMEPAGE_VAR_JDOWNLOADER_PASSWORD}}
            client: JDownloader@Docker

- Gaming:
    - Pterodactyl:
        icon: pterodactyl.png
        description: Game server manager
        href: https://pterodactyl.home.fari.ar
        container: pterodactyl
        server: docker-proxy-local
        widget:
            type: pterodactyl
            url: http://pterodactyl:1232
            key: {{HOMEPAGE_VAR_PTERODACTYL_API_KEY}}

- Work:
    - Gitea:
        icon: gitea.png
        description: Git server
        href: https://git.home.fari.ar
        container: gitea
        server: docker-proxy-local
        widget:
            type: gitea
            url: http://gitea:3000
            key: {{HOMEPAGE_VAR_GITEA_API_KEY}}
    - Stirling:
        icon: https://raw.githubusercontent.com/Stirling-Tools/Stirling-PDF/main/docs/stirling.png
        description: PDF toolbox
        href: https://stirling.home.fari.ar
        container: stirling
        server: docker-proxy-local
    - Cyberchef:
        icon: cyberchef.png
        description: The Cyber Swiss Army Knife
        href: https://cyberchef.home.fari.ar
        container: cyberchef
        server: docker-proxy-local
    - IT-Tools:
        icon: it-tools.png
        description: Online tools for developers
        href: https://it-tools.home.fari.ar
        container: it-tools
        server: docker-proxy-local

- Network:
    - Caddy:
        icon: caddy.png
        description: Reverse Proxy
        widget:
            type: caddy
            url: http://caddy:2019
    - Technitium:
        icon: technitium.png
        description: DNS Server and AdBlocker
        href: https://dns.home.fari.ar
        container: dns-server
        server: docker-proxy-local
        widget:
            type: customapi
            url: http://dns-server:5380/api/dashboard/stats/get?token={{HOMEPAGE_VAR_TECHNITIUM_TOKEN}}&type=LastDay
            refreshInterval: 10 
            method: GET 
            mappings:
                - field:
                    response:
                        stats: totalQueries
                  label: Total
                  format: number
                - field:
                    response:
                        stats: totalAuthoritative
                  label: Authoritative
                  format: number
                - field:
                    response:
                        stats: totalRecursive
                  label: Recursive
                  format: number
                - field:
                    response:
                        stats: totalBlocked
                  label: Blocked
                  format: number
    - Speedtest Tracker:
        icon: speedtest-tracker.png
        description: Internet performance tracking
        href: https://speedtest.home.fari.ar
        container: speedtest-tracker
        server: docker-proxy-local
        widget:
            type: speedtest
            url: http://speedtest-tracker:80

- Virtualization:
    - Proxmox:
        icon: proxmox.png
        description: Hypervisor management
        href: https://proxmox.home.fari.ar
        widget:
            type: proxmox
            url: https://{{HOMEPAGE_VAR_ATHENA_IP}}:8006
            username: api@pam!homepage
            password: {{HOMEPAGE_VAR_PROXMOX_API_KEY}}
            node: athena # optional
    - Portainer:
        icon: portainer.png
        description: Docker management
        href: https://portainer.home.fari.ar
        container: portainer
        server: docker-proxy-local
        widget:
            type: portainer
            url: http://portainer:9000
            env: 1
            key: {{HOMEPAGE_VAR_PORTAINER_API_KEY}}
- Athena:
    - Info:
        widget:
            type: glances
            url: http://{{HOMEPAGE_VAR_ATHENA_IP}}:61208
            metric: info
    - CPU:
        widget:
            type: glances
            url: http://{{HOMEPAGE_VAR_ATHENA_IP}}:61208
            metric: cpu
    - CPU Temp:
        widget:
            type: glances
            url: http://{{HOMEPAGE_VAR_ATHENA_IP}}:61208
            metric: sensor:Composite
    - Memory:
        widget:
            type: glances
            url: http://{{HOMEPAGE_VAR_ATHENA_IP}}:61208
            metric: memory
    - SSD:
        widget:
            type: glances
            url: http://{{HOMEPAGE_VAR_ATHENA_IP}}:61208
            metric: disk:nvme0n1
    - ZFS:
        widget:
            type: glances
            url: http://{{HOMEPAGE_VAR_ATHENA_IP}}:61208
            metric: disk:zd0
    - Network:
        widget:
            type: glances
            url: http://{{HOMEPAGE_VAR_ATHENA_IP}}:61208
            metric: network:vmbr0
- Artemis:
    - Info:
        widget:
            type: glances
            url: http://{{HOMEPAGE_VAR_ARTEMIS_IP}}:61208
            metric: info
    - CPU:
        widget:
            type: glances
            url: http://{{HOMEPAGE_VAR_ARTEMIS_IP}}:61208
            metric: cpu
    - Memory:
        widget:
            type: glances
            url: http://{{HOMEPAGE_VAR_ARTEMIS_IP}}:61208
            metric: memory
    - Root:
        widget:
            type: glances
            url: http://{{HOMEPAGE_VAR_ARTEMIS_IP}}:61208
            metric: fs:/
    - Storage:
        widget:
            type: glances
            url: http://{{HOMEPAGE_VAR_ARTEMIS_IP}}:61208
            metric: fs:/mnt/storage
- Dionysus:
    - Info:
        widget:
            type: glances
            url: http://{{HOMEPAGE_VAR_DIONYSUS_IP}}:61208
            metric: info
    - CPU:
        widget:
            type: glances
            url: http://{{HOMEPAGE_VAR_DIONYSUS_IP}}:61208
            metric: cpu
    - Memory:
        widget:
            type: glances
            url: http://{{HOMEPAGE_VAR_DIONYSUS_IP}}:61208
            metric: memory
    - Root:
        widget:
            type: glances
            url: http://{{HOMEPAGE_VAR_DIONYSUS_IP}}:61208
            metric: fs:/
